<template>
 <div>
  <v-card
   class="mx-auto"
   max-width="500">
   <v-list>
    <v-list-item-group
     color="green">
      <v-list-item>
       <v-list-item-content>
        <v-list-item-title
         class="text-center">
        {{name}}
        </v-list-item-title>
       </v-list-item-content>
      </v-list-item>
    </v-list-item-group>
   </v-list>
  </v-card>
 </div>
</template>
<script>
export default {
 props:{
  name:String,
 }
}
</script>